// albumsData.js
const albumsData = [
  {
    id: 1,
    title: 'Taylor Swift',
    artist: 'Taylor Swift',
    songs: [
      { id: 101, title: 'Tim McGraw' },
      { id: 102, title: 'Picture To Burn' },
      { id: 103, title: 'Teardrops On My Guitar' },
      { id: 104, title: 'A Place In This World' },
      { id: 105, title: 'Cold As You' },
      { id: 106, title: 'The Outside' },
      { id: 107, title: 'Tied Together With A Smile' },
      { id: 108, title: 'Stay Beautiful' },
      { id: 109, title: 'Should’ve Said No' },
      { id: 110, title: 'Mary’s Song (Oh My My My)' },
      { id: 111, title: 'Our Song' },
      { id: 112, title: 'I’m Only Me When I’m With You' },
      { id: 113, title: 'Invisible' },
      { id: 114, title: 'A Perfectly Good Heart' },
    ],
  },
  {
    id: 2,
    title: 'Fearless',
    artist: 'Taylor Swift',
    songs: [
      { id: 201, title: 'Fearless' },
      { id: 202, title: 'Fifteen' },
      { id: 203, title: 'Love Story' },
      { id: 204, title: 'Hey Stephen' },
      { id: 205, title: 'White Horse' },
      { id: 206, title: 'You Belong With Me' },
      { id: 207, title: 'Breathe' },
      { id: 208, title: 'Tell Me Why' },
      { id: 209, title: 'You’re Not Sorry' },
      { id: 210, title: 'The Way I Loved You' },
      { id: 211, title: 'Forever & Always' },
      { id: 212, title: 'The Best Day' },
      { id: 213, title: 'Change' },
      { id: 214, title: 'Jump Then Fall' },
      { id: 215, title: 'Untouchable' },
      { id: 216, title: 'Forever & Always PV' },
      { id: 217, title: 'Come In With The Rain' },
      { id: 218, title: 'Superstar' },
      { id: 219, title: 'The Other Side Of The Door' },
      { id: 220, title: 'Today Was a Fairytale' },
      { id: 221, title: 'You All Over Me' },
      { id: 222, title: 'Mr. Perfectly Fine' },
      { id: 223, title: 'We Were Happy' },
      { id: 224, title: 'That’s When' },
      { id: 225, title: 'Don’t You' },
      { id: 226, title: 'Bye Bye Baby' },
    ],
  },
  {
    id: 3,
    title: 'Speak Now',
    artist: 'Taylor Swift',
    songs: [
      { id: 301, title: 'Mine' },
      { id: 302, title: 'Sparks Fly' },
      { id: 303, title: 'Back To December' },
      { id: 304, title: 'Speak Now' },
      { id: 305, title: 'Dear John' },
      { id: 306, title: 'Mean' },
      { id: 307, title: 'The Story Of Us' },
      { id: 308, title: 'Never Grow Up' },
      { id: 309, title: 'Enchanted' },
      { id: 310, title: 'Better Than Revenge' },
      { id: 311, title: 'Innocent' },
      { id: 312, title: 'Haunted' },
      { id: 313, title: 'Last Kiss' },
      { id: 314, title: 'Long Live' },
      { id: 315, title: 'Ours (Deluxe)' },
      { id: 316, title: 'If This Was A Movie' },
      { id: 317, title: 'Superman' },
      { id: 318, title: 'Back To December – AV' },
      { id: 319, title: 'Haunted AV' },
      { id: 320, title: 'Electric Touch' },
      { id: 321, title: 'When Emma Falls In Love' },
      { id: 322, title: 'I Can See You' },
      { id: 323, title: 'Castles Crumbling' },
      { id: 324, title: 'Foolish One' },
      { id: 325, title: 'Timeless' },
    ],
  },
  {
    id: 4,
    title: 'Red',
    artist: 'Taylor Swift',
    songs: [
      { id: 401, title: 'State of Grace' },
      { id: 402, title: 'Red' },
      { id: 403, title: 'Treacherous' },
      { id: 404, title: 'I Knew You Were Trouble' },
      { id: 405, title: 'All Too Well' },
      { id: 406, title: '22' },
      { id: 407, title: 'I Almost Do' },
      { id: 408, title: 'We Are Never Ever Getting Back Together' },
      { id: 409, title: 'Stay Stay Stay' },
      { id: 410, title: 'The Last Time' },
      { id: 411, title: 'Holy Ground' },
      { id: 412, title: 'Sad Beautiful Tragic' },
      { id: 413, title: 'The Lucky One' },
      { id: 414, title: 'Everything Has Changed' },
      { id: 415, title: 'Starlight' },
      { id: 416, title: 'Begin Again' },
      { id: 417, title: 'The Moment I Knew' },
      { id: 418, title: 'Come Back…Be Here' },
      { id: 419, title: 'Girl At Home' },
      { id: 420, title: 'State of Grace AV' },
      { id: 421, title: 'Ronan' },
      { id: 422, title: 'Better Man' },
      { id: 423, title: 'Nothing New' },
      { id: 424, title: 'Babe' },
      { id: 425, title: 'Message in A Bottle' },
      { id: 426, title: 'I Bet You Think About Me' },
      { id: 427, title: 'Forever Winter' },
      { id: 428, title: 'Run' },
      { id: 429, title: 'The Very First Night' },
      { id: 430, title: 'All Too Well 10MV' },
      { id: 431, title: 'Eyes Open' },
      { id: 432, title: 'Safe and Sound' },
    ],
  },
  {
    id: 5,
    title: '1989',
    artist: 'Taylor Swift',
    songs: [
      { id: 501, title: 'Welcome to New York' },
      { id: 502, title: 'Blank Space' },
      { id: 503, title: 'Style' },
      { id: 504, title: 'Out of the Woods' },
      { id: 505, title: 'All You Had to Do Was Stay' },
      { id: 506, title: 'Shake It Off' },
      { id: 507, title: 'I Wish You Would' },
      { id: 508, title: 'Bad Blood' },
      { id: 509, title: 'Wildest Dreams' },
      { id: 510, title: 'How You Get the Girl' },
      { id: 511, title: 'This Love' },
      { id: 512, title: 'I Know Places' },
      { id: 513, title: 'Clean' },
      { id: 514, title: 'Wonderland' },
      { id: 515, title: 'You Are In Love' },
      { id: 516, title: 'New Romantics' },
      { id: 517, title: 'Slut!' },
      { id: 518, title: 'Say Don\'t Go' },
      { id: 519, title: 'Now That We Don\'t Talk' },
      { id: 520, title: 'Suburban Legends' },
      { id: 521, title: 'Is it over now?' },
      { id: 522, title: 'Sweeter Than Fiction' },
    ],
  },
  {
    id: 6,
    title: 'reputation',
    artist: 'Taylor Swift',
    songs: [
      { id: 601, title: '…Ready For it?' },
      { id: 602, title: 'End Game' },
      { id: 603, title: 'I Did Something Bad' },
      { id: 604, title: 'Don’t Blame Me' },
      { id: 605, title: 'Delicate' },
      { id: 606, title: 'Look What You Made Me Do' },
      { id: 607, title: 'So It Goes…' },
      { id: 608, title: 'Gorgeous' },
      { id: 609, title: 'Getaway Car' },
      { id: 610, title: 'King Of My Heart' },
      { id: 611, title: 'Dancing With Our Hands Tied' },
      { id: 612, title: 'Dress' },
      { id: 613, title: 'This Is Why We Can’t Have Nice Things' },
      { id: 614, title: 'Call It What You Want' },
      { id: 615, title: 'New Year’s Day' },
    ],
  },
  {
    id: 7,
    title: 'Lover',
    artist: 'Taylor Swift',
    songs: [
      { id: 701, title: 'I Forgot That You Existed' },
      { id: 702, title: 'Cruel Summer' },
      { id: 703, title: 'Lover' },
      { id: 704, title: 'The Man' },
      { id: 705, title: 'The Archer' },
      { id: 706, title: 'I Think He Knows' },
      { id: 707, title: 'Miss Americana & The Heartbreak Prince' },
      { id: 708, title: 'Paper Rings' },
      { id: 709, title: 'Cornelia Street' },
      { id: 710, title: 'Death By A Thousand Cuts' },
      { id: 711, title: 'London Boy' },
      { id: 712, title: 'Soon You’ll Get Better' },
      { id: 713, title: 'False God' },
      { id: 714, title: 'You Need To Calm Down' },
      { id: 715, title: 'Afterglow' },
      { id: 716, title: 'ME!' },
      { id: 717, title: 'It’s Nice To Have A Friend' },
      { id: 718, title: 'Daylight' },
      { id: 719, title: 'All Of The Girls You\'ve Loved Before' },
    ],
  },
  {
    id: 8,
    title: 'folklore',
    artist: 'Taylor Swift',
    songs: [
      { id: 801, title: 'the 1' },
      { id: 802, title: 'cardigan' },
      { id: 803, title: 'the last great american dynasty' },
      { id: 804, title: 'exile (feat. Bon Iver)' },
      { id: 805, title: 'my tears ricochet' },
      { id: 806, title: 'mirrorball' },
      { id: 807, title: 'seven' },
      { id: 808, title: 'august' },
      { id: 809, title: 'this is me trying' },
      { id: 810, title: 'illicit affairs' },
      { id: 811, title: 'invisible string' },
      { id: 812, title: 'mad woman' },
      { id: 813, title: 'epiphany' },
      { id: 814, title: 'betty' },
      { id: 815, title: 'peace' },
      { id: 816, title: 'hoax' },
      { id: 817, title: 'the lakes' },
    ],
  },
  {
    id: 9,
    title: 'evermore',
    artist: 'Taylor Swift',
    songs: [
      { id: 901, title: 'willow' },
      { id: 902, title: 'champagne problems' },
      { id: 903, title: 'gold rush' },
      { id: 904, title: '’tis the damn season' },
      { id: 905, title: 'tolerate it' },
      { id: 906, title: 'no body, no crime' },
      { id: 907, title: 'happiness' },
      { id: 908, title: 'dorothea' },
      { id: 909, title: 'coney island' },
      { id: 910, title: 'ivy' },
      { id: 911, title: 'cowboy like me' },
      { id: 912, title: 'long story short' },
      { id: 913, title: 'marjorie' },
      { id: 914, title: 'closure' },
      { id: 915, title: 'evermore' },
      { id: 916, title: 'right where you left me' },
      { id: 917, title: 'it’s time to go' },
    ],
  },
  {
    id: 10,
    title: 'Midnights',
    artist: 'Taylor Swift',
    songs: [
      { id: 1001, title: 'Lavender Haze' },
      { id: 1002, title: 'Maroon' },
      { id: 1003, title: 'Anti-Hero' },
      { id: 1004, title: 'Snow On The Beach' },
      { id: 1005, title: 'You’re On Your Own, Kid' },
      { id: 1006, title: 'Midnight Rain' },
      { id: 1007, title: 'Question…?' },
      { id: 1008, title: 'Vigilante Sh*t' },
      { id: 1009, title: 'Bejeweled' },
      { id: 1010, title: 'Labyrinth' },
      { id: 1011, title: 'Karma' },
      { id: 1012, title: 'Sweet Nothing' },
      { id: 1013, title: 'Mastermind' },
      { id: 1014, title: 'The Great War' },
      { id: 1015, title: 'Bigger Than the Whole Sky' },
      { id: 1016, title: 'Paris' },
      { id: 1017, title: 'High Infidelity' },
      { id: 1018, title: 'Glitch' },
      { id: 1019, title: 'Would’ve, Could’ve, Should’ve' },
      { id: 1020, title: 'Dear Reader' },
      { id: 1021, title: 'Hits Different' },
      { id: 1022, title: 'You\'re Losing Me' },
    ],
  },
  // Add more albums as needed
];

export default albumsData;
